In [1]:
# Last technique for data proprocessing using mean and Median
# 8th interview-
# why mean and median used for data preprocessing
# they work with numerical data only
# mean and median always working in data preprocessing for NaN value not for 0
import numpy as np 
import pandas as pd

In [2]:
data={
    "age":[20,21,np.nan,22,21],
    "marks":[80,90,np.nan,75,np.nan]
    }
df=pd.DataFrame(data)
df

    age  marks
0  20.0   80.0
1  21.0   90.0
2   NaN    NaN
3  22.0   75.0
4  21.0    NaN

In [4]:
df["age"]= df["age"].mean()
df

    age  marks
0  21.0   80.0
1  21.0   90.0
2  21.0    NaN
3  21.0   75.0
4  21.0    NaN

In [9]:
df["marks"]= df["marks"].fillna(df["marks"].median())
df

    age  marks
0  21.0   80.0
1  21.0   80.0
2  21.0   80.0
3  21.0   80.0
4  21.0   80.0

In [6]:
# 30 records with missing values 
# student marks phy che math bio english with none values

In [10]:
df=pd.read_csv('student_marks_missing_30_records.csv')
df

    student_id student_name   phy   che  math   bio  english
0            1        Aarav  83.0  73.0  59.0  87.0     52.0
1            2       Vihaan  65.0  83.0   NaN  67.0     55.0
2            3       Aditya  55.0  68.0  80.0  84.0     68.0
3            4        Arjun  47.0  66.0  46.0  68.0      NaN
4            5      Reyansh  74.0  82.0  46.0  65.0     77.0
5            6        Kabir  56.0   NaN  88.0  69.0     93.0
6            7       Vivaan  71.0  86.0  72.0  60.0     59.0
7            8       Atharv  91.0  95.0  88.0   NaN     81.0
8            9       Ishaan  95.0  51.0  65.0  53.0     83.0
9           10      Krishna   NaN  48.0  69.0  58.0     94.0
10          11        Rohan  53.0  70.0  46.0  64.0      NaN
11          12        Ayaan  91.0  51.0  88.0  52.0     91.0
12          13        Dhruv  79.0  58.0   NaN  80.0     94.0
13          14        Kunal  84.0  48.0  46.0  50.0     86.0
14          15        Rahul  48.0   NaN  62.0  70.0     88.0
15          16       Ananya  78.0  54.0  80.0  58.0     75.0
16          17         Diya  92.0  59.0  52.0   NaN     67.0
17          18       Aadhya  84.0  65.0  60.0  89.0     62.0
18          19          Ira   NaN  68.0  70.0  69.0     89.0
19          20         Myra  85.0  73.0  59.0  89.0      NaN
20          21       Saanvi  69.0  51.0  53.0  68.0     45.0
21          22        Kiara  88.0  52.0   NaN  55.0     95.0
22          23         Avni  61.0  52.0  79.0  79.0     77.0
23          24        Anika  49.0   NaN  83.0  85.0     72.0
24          25        Meera  51.0  53.0  52.0  56.0     78.0
25          26         Riya  77.0  92.0  67.0   NaN     81.0
26          27        Tanya  79.0  88.0  84.0  66.0     71.0
27          28        Nisha   NaN  45.0  79.0  81.0     91.0
28          29         Pihu  58.0  47.0  45.0  49.0      NaN
29          30         Sara  58.0  83.0   NaN  53.0     59.0

In [11]:
df["phy"]= df["phy"].fillna(df["phy"].median())
df

    student_id student_name   phy   che  math   bio  english
0            1        Aarav  83.0  73.0  59.0  87.0     52.0
1            2       Vihaan  65.0  83.0   NaN  67.0     55.0
2            3       Aditya  55.0  68.0  80.0  84.0     68.0
3            4        Arjun  47.0  66.0  46.0  68.0      NaN
4            5      Reyansh  74.0  82.0  46.0  65.0     77.0
5            6        Kabir  56.0   NaN  88.0  69.0     93.0
6            7       Vivaan  71.0  86.0  72.0  60.0     59.0
7            8       Atharv  91.0  95.0  88.0   NaN     81.0
8            9       Ishaan  95.0  51.0  65.0  53.0     83.0
9           10      Krishna  74.0  48.0  69.0  58.0     94.0
10          11        Rohan  53.0  70.0  46.0  64.0      NaN
11          12        Ayaan  91.0  51.0  88.0  52.0     91.0
12          13        Dhruv  79.0  58.0   NaN  80.0     94.0
13          14        Kunal  84.0  48.0  46.0  50.0     86.0
14          15        Rahul  48.0   NaN  62.0  70.0     88.0
15          16       Ananya  78.0  54.0  80.0  58.0     75.0
16          17         Diya  92.0  59.0  52.0   NaN     67.0
17          18       Aadhya  84.0  65.0  60.0  89.0     62.0
18          19          Ira  74.0  68.0  70.0  69.0     89.0
19          20         Myra  85.0  73.0  59.0  89.0      NaN
20          21       Saanvi  69.0  51.0  53.0  68.0     45.0
21          22        Kiara  88.0  52.0   NaN  55.0     95.0
22          23         Avni  61.0  52.0  79.0  79.0     77.0
23          24        Anika  49.0   NaN  83.0  85.0     72.0
24          25        Meera  51.0  53.0  52.0  56.0     78.0
25          26         Riya  77.0  92.0  67.0   NaN     81.0
26          27        Tanya  79.0  88.0  84.0  66.0     71.0
27          28        Nisha  74.0  45.0  79.0  81.0     91.0
28          29         Pihu  58.0  47.0  45.0  49.0      NaN
29          30         Sara  58.0  83.0   NaN  53.0     59.0

In [13]:
df[["che", "bio","math","english"]] = df[["che", "bio","math","english"]].fillna(
    df[["che", "bio","math","english"]].median()
)

df

    student_id student_name   phy   che  math   bio  english
0            1        Aarav  83.0  73.0  59.0  87.0     52.0
1            2       Vihaan  65.0  83.0  66.0  67.0     55.0
2            3       Aditya  55.0  68.0  80.0  84.0     68.0
3            4        Arjun  47.0  66.0  46.0  68.0     77.5
4            5      Reyansh  74.0  82.0  46.0  65.0     77.0
5            6        Kabir  56.0  65.0  88.0  69.0     93.0
6            7       Vivaan  71.0  86.0  72.0  60.0     59.0
7            8       Atharv  91.0  95.0  88.0  67.0     81.0
8            9       Ishaan  95.0  51.0  65.0  53.0     83.0
9           10      Krishna  74.0  48.0  69.0  58.0     94.0
10          11        Rohan  53.0  70.0  46.0  64.0     77.5
11          12        Ayaan  91.0  51.0  88.0  52.0     91.0
12          13        Dhruv  79.0  58.0  66.0  80.0     94.0
13          14        Kunal  84.0  48.0  46.0  50.0     86.0
14          15        Rahul  48.0  65.0  62.0  70.0     88.0
15          16       Ananya  78.0  54.0  80.0  58.0     75.0
16          17         Diya  92.0  59.0  52.0  67.0     67.0
17          18       Aadhya  84.0  65.0  60.0  89.0     62.0
18          19          Ira  74.0  68.0  70.0  69.0     89.0
19          20         Myra  85.0  73.0  59.0  89.0     77.5
20          21       Saanvi  69.0  51.0  53.0  68.0     45.0
21          22        Kiara  88.0  52.0  66.0  55.0     95.0
22          23         Avni  61.0  52.0  79.0  79.0     77.0
23          24        Anika  49.0  65.0  83.0  85.0     72.0
24          25        Meera  51.0  53.0  52.0  56.0     78.0
25          26         Riya  77.0  92.0  67.0  67.0     81.0
26          27        Tanya  79.0  88.0  84.0  66.0     71.0
27          28        Nisha  74.0  45.0  79.0  81.0     91.0
28          29         Pihu  58.0  47.0  45.0  49.0     77.5
29          30         Sara  58.0  83.0  66.0  53.0     59.0